body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Beszel is this about?
      options:
        - Hub
        - Agent
        - Hub & Agent
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the solution or feature you'd like. Explain what problem this solves or what value it adds.
        **Important:** Be specific and detailed. Vague requests like "make it better" will be closed.
      placeholder: |
        Example:
        - What is the feature?
        - What problem does it solve?
        - How should it work?
    validations:
      required: true
